<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXxVNfOl\App_AppDevContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXxVNfOl/App_AppDevContainer.php') {
    touch(__DIR__.'/ContainerXxVNfOl.legacy');

    return;
}

if (!\class_exists(App_AppDevContainer::class, false)) {
    \class_alias(\ContainerXxVNfOl\App_AppDevContainer::class, App_AppDevContainer::class, false);
}

return new \ContainerXxVNfOl\App_AppDevContainer([
    'container.build_hash' => 'XxVNfOl',
    'container.build_id' => 'a361c85e',
    'container.build_time' => 1614151545,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXxVNfOl');
